graph TD;
    2783202["2783202<br>commit4<br>.gitattributes<br>test2.txt<br>test4.txt"]
    a74e491 --> 2783202
    a74e491["a74e491<br>commit3<br>.gitattributes<br>test2.txt<br>test3.txt"]
    8c0798c --> a74e491
    8c0798c["8c0798c<br>commit2<br>.gitattributes<br>test1.txt<br>test2.txt"]
    1aa374f --> 8c0798c
    1aa374f["1aa374f<br>commit1<br>.gitattributes<br>test1.txt"]
    585071c --> 1aa374f
    585071c["585071c<br>Initial commit<br>.gitattributes"]