graph TD;
    585071c["Initial commit"]
    1aa374f["commit1"]
    585071c --> 1aa374f
    file_test1_txt["test1.txt"]
    1aa374f --> file_test1_txt
    8c0798c["commit2"]
    1aa374f --> 8c0798c
    file_test1_txt["test1.txt"]
    8c0798c --> file_test1_txt
    file_test2_txt["test2.txt"]
    8c0798c --> file_test2_txt
    a74e491["commit3"]
    8c0798c --> a74e491
    file_test1_txt["test1.txt"]
    a74e491 --> file_test1_txt
    file_test3_txt["test3.txt"]
    a74e491 --> file_test3_txt
    2783202["commit4"]
    a74e491 --> 2783202
    file_test2_txt["test2.txt"]
    2783202 --> file_test2_txt
    file_test3_txt["test3.txt"]
    2783202 --> file_test3_txt
    file_test4_txt["test4.txt"]
    2783202 --> file_test4_txt